services:
  annet:
    build: annet/
    command: tail -f /dev/null
    network_mode: host
    volumes:
      - type: bind
        source: ./config.yaml
        target: /config.yaml
      - type: bind
        source: ./my_generators
        target: /my_generators
    environment:
      - NETBOX_TOKEN=${NETBOX_TOKEN}
      - NETBOX_URL=${NETBOX_URL}
